apiVersion: v1
kind: Deployment
metadata:
  name: deploy-spring-devops
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-app
      spec:
        container:
          - name: spring-devops-container
            images: bingms/devops
            ports:
              - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: spring-app
  ports:
    - protocol: "TCP"
      #inside cluster port
      port: 6000
      #container port
      targetPort: 80
      #outside port
      nodePort: 30001
    type: LoadBalancer