apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-devops-deployment
  labels:
    app: spring-devops
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-devops-container
          image: bingms/devops:latest
          ports:
          - containerPort: 8080
          imagePullPolicy: Always