apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: spring-app
  ports:
    - protocol: "TCP"
      #inside cluster port
      port: 6000
      #container port
      targetPort: 8080
      #outside port
      #nodePort: 30001
  #type: LoadBalancer